
stages:
  - test
  - build
  - deploy

test:windows:386:
  stage: test
  tags:
    - windows
  script:
    - export CI_ARCH=386
    - scripts/ci-test.sh

test:windows:amd64:
  stage: test
  tags:
    - windows
  script:
    - export CI_ARCH=amd64
    - scripts/ci-test.sh

build:windows:386:
  stage: build
  tags:
    - windows
  script:
    - export CI_ARCH=386
    - scripts/ci-build.sh
  artifacts:
    paths:
      - binaries

build:windows:amd64:
  stage: build
  tags:
    - windows
  script:
    - export CI_ARCH=amd64
    - scripts/ci-build.sh
  artifacts:
    paths:
      - binaries

deploy:
  stage: deploy
  tags:
    - dropsy
  script:
    - scripts/ci-deploy.sh
  dependencies:
    - :build:windows:386
    - :build:windows:amd64
